# Generated by Django 5.1.3 on 2024-12-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_assignment_subject_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'todo', 'verbose_name_plural': 'todo'},
        ),
    ]
